/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KanbanIndexRouteImport } from './routes/kanban/index'
import { Route as KanbanKanbanIdRouteImport } from './routes/kanban.$kanbanId'

const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanIndexRoute = KanbanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KanbanRoute,
} as any)
const KanbanKanbanIdRoute = KanbanKanbanIdRouteImport.update({
  id: '/$kanbanId',
  path: '/$kanbanId',
  getParentRoute: () => KanbanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/kanban': typeof KanbanRouteWithChildren
  '/kanban/$kanbanId': typeof KanbanKanbanIdRoute
  '/kanban/': typeof KanbanIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/kanban/$kanbanId': typeof KanbanKanbanIdRoute
  '/kanban': typeof KanbanIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/kanban': typeof KanbanRouteWithChildren
  '/kanban/$kanbanId': typeof KanbanKanbanIdRoute
  '/kanban/': typeof KanbanIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/kanban' | '/kanban/$kanbanId' | '/kanban/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/kanban/$kanbanId' | '/kanban'
  id: '__root__' | '/' | '/about' | '/kanban' | '/kanban/$kanbanId' | '/kanban/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  KanbanRoute: typeof KanbanRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban/': {
      id: '/kanban/'
      path: '/'
      fullPath: '/kanban/'
      preLoaderRoute: typeof KanbanIndexRouteImport
      parentRoute: typeof KanbanRoute
    }
    '/kanban/$kanbanId': {
      id: '/kanban/$kanbanId'
      path: '/$kanbanId'
      fullPath: '/kanban/$kanbanId'
      preLoaderRoute: typeof KanbanKanbanIdRouteImport
      parentRoute: typeof KanbanRoute
    }
  }
}

interface KanbanRouteChildren {
  KanbanKanbanIdRoute: typeof KanbanKanbanIdRoute
  KanbanIndexRoute: typeof KanbanIndexRoute
}

const KanbanRouteChildren: KanbanRouteChildren = {
  KanbanKanbanIdRoute: KanbanKanbanIdRoute,
  KanbanIndexRoute: KanbanIndexRoute,
}

const KanbanRouteWithChildren =
  KanbanRoute._addFileChildren(KanbanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  KanbanRoute: KanbanRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
