/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KanbanIndexRouteImport } from './routes/kanban/index'
import { Route as KanbanKanbanIdRouteImport } from './routes/kanban.$kanbanId'
import { Route as AuthCallbackKeycloakRouteImport } from './routes/auth/callback/keycloak'
import { Route as AuthCallbackGoogleRouteImport } from './routes/auth/callback/google'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanIndexRoute = KanbanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KanbanRoute,
} as any)
const KanbanKanbanIdRoute = KanbanKanbanIdRouteImport.update({
  id: '/$kanbanId',
  path: '/$kanbanId',
  getParentRoute: () => KanbanRoute,
} as any)
const AuthCallbackKeycloakRoute = AuthCallbackKeycloakRouteImport.update({
  id: '/auth/callback/keycloak',
  path: '/auth/callback/keycloak',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackGoogleRoute = AuthCallbackGoogleRouteImport.update({
  id: '/auth/callback/google',
  path: '/auth/callback/google',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/kanban': typeof KanbanRouteWithChildren
  '/login': typeof LoginRoute
  '/kanban/$kanbanId': typeof KanbanKanbanIdRoute
  '/kanban/': typeof KanbanIndexRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
  '/auth/callback/keycloak': typeof AuthCallbackKeycloakRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/kanban/$kanbanId': typeof KanbanKanbanIdRoute
  '/kanban': typeof KanbanIndexRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
  '/auth/callback/keycloak': typeof AuthCallbackKeycloakRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/kanban': typeof KanbanRouteWithChildren
  '/login': typeof LoginRoute
  '/kanban/$kanbanId': typeof KanbanKanbanIdRoute
  '/kanban/': typeof KanbanIndexRoute
  '/auth/callback/google': typeof AuthCallbackGoogleRoute
  '/auth/callback/keycloak': typeof AuthCallbackKeycloakRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/kanban'
    | '/login'
    | '/kanban/$kanbanId'
    | '/kanban/'
    | '/auth/callback/google'
    | '/auth/callback/keycloak'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/kanban/$kanbanId'
    | '/kanban'
    | '/auth/callback/google'
    | '/auth/callback/keycloak'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/kanban'
    | '/login'
    | '/kanban/$kanbanId'
    | '/kanban/'
    | '/auth/callback/google'
    | '/auth/callback/keycloak'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  KanbanRoute: typeof KanbanRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackGoogleRoute: typeof AuthCallbackGoogleRoute
  AuthCallbackKeycloakRoute: typeof AuthCallbackKeycloakRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban/': {
      id: '/kanban/'
      path: '/'
      fullPath: '/kanban/'
      preLoaderRoute: typeof KanbanIndexRouteImport
      parentRoute: typeof KanbanRoute
    }
    '/kanban/$kanbanId': {
      id: '/kanban/$kanbanId'
      path: '/$kanbanId'
      fullPath: '/kanban/$kanbanId'
      preLoaderRoute: typeof KanbanKanbanIdRouteImport
      parentRoute: typeof KanbanRoute
    }
    '/auth/callback/keycloak': {
      id: '/auth/callback/keycloak'
      path: '/auth/callback/keycloak'
      fullPath: '/auth/callback/keycloak'
      preLoaderRoute: typeof AuthCallbackKeycloakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback/google': {
      id: '/auth/callback/google'
      path: '/auth/callback/google'
      fullPath: '/auth/callback/google'
      preLoaderRoute: typeof AuthCallbackGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KanbanRouteChildren {
  KanbanKanbanIdRoute: typeof KanbanKanbanIdRoute
  KanbanIndexRoute: typeof KanbanIndexRoute
}

const KanbanRouteChildren: KanbanRouteChildren = {
  KanbanKanbanIdRoute: KanbanKanbanIdRoute,
  KanbanIndexRoute: KanbanIndexRoute,
}

const KanbanRouteWithChildren =
  KanbanRoute._addFileChildren(KanbanRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  KanbanRoute: KanbanRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackGoogleRoute: AuthCallbackGoogleRoute,
  AuthCallbackKeycloakRoute: AuthCallbackKeycloakRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
